const urls = [


     { url: 'https://www.koton.com/kadin-ayakkabi'},
    { url: 'https://www.koton.com/kadin-canta'},
    {url:'https://www.koton.com/kadin-cuzdan'},
    { url: 'https://www.koton.com/kadin-parfum'},
    { url: 'https://www.koton.com/kadin-kemer'},
    { url: 'https://www.koton.com/kadin-corap'},
    { url: 'https://www.koton.com/kadin-cuzdan'},
    { url: 'https://www.koton.com/kadin-taki'},

    { url: 'https://www.koton.com/kadin-sapka'},
    { url: 'https://www.koton.com/kadin-sac-aksesuarlari'},
    { url: 'https://www.koton.com/kadin-kozmetik'},
    { url: 'https://www.koton.com/kadin-sal'},
    {url:'https://www.koton.com/kadife-elbise-kadin'},

    {url:'https://www.koton.com/kadin-spor-giyim'},
    {url:'https://www.koton.com/kadin-elbise'},
    {url:'https://www.koton.com/kadin-pantolon'},
    {url:'https://www.koton.com/kadin-tisort'},
    {url:'https://www.koton.com/kadin-etek'},
    {url:'https://www.koton.com/kadin-atlet'},
    {url:'https://www.koton.com/kadin-sort'},
    {url:'https://www.koton.com/kadin-gomlek'},
    {url:'https://www.koton.com/kadin-crop-ustler'},
    {url:'https://www.koton.com/kadin-keten-koleksiyonu'},
    {url:'https://www.koton.com/kadin-yelek'},
    {url:'https://www.koton.com/kadin-tulum'},
    {url:'https://www.koton.com/kadin-tunik'},
    {url:'https://www.koton.com/kadin-sweatshirt'},
    {url:'https://www.koton.com/kadin-esofman-alti'},
    {url:'https://www.koton.com/kadin-koton-jeans'},
    {url:'https://www.koton.com/kadin-abiye-davet'},
    {url:'https://www.koton.com/plaj-giyim-kadin'},
    {url:'https://www.koton.com/bikini-takimi-kadin'},
    {url:'https://www.koton.com/kadin-mayo'},
    {url:'https://www.koton.com/kadin-blazer-ceket'},
    {url:'https://www.koton.com/kadin-bluz'},
    {url:'https://www.koton.com/kargo-parasut'},
    {url:'https://www.koton.com/kadin-kot-ceket'},
    {url:'https://www.koton.com/kadin-kot-sort'},
    {url:'https://www.koton.com/kadin-tayt'},
    {url:'https://www.koton.com/kadin-dis-giyim'},
    {url:'https://www.koton.com/kadin-trenckot'},
    {url:'https://www.koton.com/sisme-yelek-kadin'},

]

module.exports={urls}